---
- name: Module Director | Ensure config directory
  ansible.builtin.file:
    state: directory
    dest: "{{ icingaweb2_modules_config_dir }}/director"
    owner: "{{ icingaweb2_httpd_user }}"
    group: "{{ icingaweb2_group }}"
    mode: "2770"

- name: Module Director | Manage config files
  ansible.builtin.include_tasks: manage_module_config.yml
  loop: "{{ _files }}"
  loop_control:
    loop_var: _file
  when: vars['icingaweb2_modules'][_module][_file] is defined
  vars:
    _module: "{{ item.key }}"
    _files:
      - kickstart
      - config

- name: Module Director | Manage Schema
  when: icingaweb2_modules['director']['import_schema'] | default(false)
  block:
    - name: Module Director | Prepare _db informations
      ansible.builtin.set_fact:
        _db:
          host: "{{ icingaweb2_resources['director_db']['host'] | default('localhost') }}"
          port: "{{ icingaweb2_resources['director_db']['port'] | default('3306') }}"
          user: "{{ icingaweb2_resources['director_db']['user'] | default('director') }}"
          password: "{{ icingaweb2_resources['director_db']['password'] | default(omit) }}"
          name: "{{ icingaweb2_resources['director_db']['dbname'] | default('director') }}"
          ssl_mode: "{{ icingaweb2_resources['director_db']['ssl_mode'] | default(omit) }}"
          ssl_ca: "{{ icingaweb2_resources['director_db']['ssl_ca'] | default(omit) }}"
          ssl_cert: "{{ icingaweb2_resources['director_db']['ssl_cert'] | default(omit) }}"
          ssl_key: "{{ icingaweb2_resources['director_db']['ssl_key'] | default(omit) }}"
          ssl_cipher: "{{ icingaweb2_resources['director_db']['ssl_cipher'] | default(omit) }}"
          ssl_extra_options: "{{ icingaweb2_resources['director_db']['ssl_extra_options'] | default(omit) }}"
          schema_path_mysql: /usr/share/icingaweb2/modules/director/schema/mysql.schema.sql
          schema_path_pgsql: /usr/share/icingaweb2/modules/director/schema/pgsql.schema.sql
          select_query: "select * from director"
          type: "{{ icingaweb2_resources['director_db']['type'] | default(omit) }}"

    - ansible.builtin.fail:
        fail_msg: No database type was provided
      when: icingaweb2_resources['director_db']['type'] is not defined

    - ansible.builtin.fail:
        fail_msg: "Invalid database type was provided. [Supported: mysql, pgsql]"
      when: _db.type not in ['mysql', 'pgsql']

    - name: Module Director | Import MySQL Schema
      ansible.builtin.include_tasks: ../manage_mysql_imports.yml
      when: _db.type == 'mysql'

    - name: Module Director | empty _db var
      ansible.builtin.set_fact:
        _db: {}

- name: Module Director | Check for pending migrations  # noqa: command-instead-of-shell
  ansible.builtin.shell:
    cmd: icingacli director migration pending
  register: _pending
  changed_when: _pending.rc|int == 0
  failed_when: _pending.stdout|length > 0
  when: vars['icingaweb2_modules']['director']['import_schema'] is defined and icingaweb2_modules.director.import_schema and vars['icingaweb2_modules']['director']['config'] is defined

- name: Module Director | Apply pending migrations  # noqa: command-instead-of-shell
  ansible.builtin.shell:
    cmd: icingacli director migration run
  when: vars['icingaweb2_modules']['director']['import_schema'] is defined and icingaweb2_modules.director.import_schema and vars['icingaweb2_modules']['director']['config'] is defined and _pending.rc|int == 0

- name: Module Director | Check if kickstart is required  # noqa: command-instead-of-shell
  ansible.builtin.shell:
    cmd: icingacli director kickstart required
  register: _required
  changed_when: _required.rc|int == 0
  failed_when: _required.rc|int >= 2
  when: vars['icingaweb2_modules']['director']['run_kickstart'] is defined and icingaweb2_modules.director.run_kickstart and vars['icingaweb2_modules']['director']['kickstart'] is defined

- name: Module Director | Run kickstart if required  # noqa: command-instead-of-shell
  ansible.builtin.shell:
    cmd: icingacli director kickstart run
  when: vars['icingaweb2_modules']['director']['run_kickstart'] is defined and icingaweb2_modules.director.run_kickstart and vars['icingaweb2_modules']['director']['kickstart'] is defined and _required.rc|int == 0

- name: Module Director | Ensure installation from source is complete
  when: icingaweb2_modules['director']['source'] == 'git'
  block:
    - name: Module Director | Ensure daemon user exists
      ansible.builtin.user:
        name: icingadirector
        state: present
        shell: /bin/nologin
        system: yes
        home: /var/lib/icingadirector
        group: "{{ icingaweb2_group }}"

    - name: Module Director | Ensure home directory exists
      ansible.builtin.file:
        state: directory
        dest: /var/lib/icingadirector
        owner: icingadirector
        group: "{{ icingaweb2_group }}"
        mode: "0750"

    - name: Module Director | Ensure systemd unit file exists
      ansible.builtin.copy:
        src: "{{ icingaweb2_config.global.module_path }}/director/contrib/systemd/icinga-director.service"
        dest: /etc/systemd/system/icingadirector.service
        owner: root
        group: root
        mode: "0644"
        remote_src: yes
