---
- name: Include OS specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"

- name: Apt - install common packages
  ansible.builtin.apt:
    pkg: "{{ icinga2_common_packages }}"
    state: present

- name: Install Vim
  ansible.builtin.include_tasks: vim.yml
  when: icinga2_common_install_vim